MODELS:
  FASTER_RCNN_R_50_FPN_1X:
    # Change _BASE_ path to your own path (/home/<user>/Mosquitoes/<pasta_experimento>/configs/faster_rcnn_R_50_FPN_1X/Base-RCNN-FPN.yaml)
    _BASE_: "/home/umberto.pereira/Mosquitoes/SIAC_2024/configs/Base-RCNN-FPN.yaml"
    MODEL:
      WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl"
      MASK_ON: False # True or False
      RPN:
        PRE_NMS_TOPK_TRAIN: 600
        PRE_NMS_TOPK_TEST:  300
        POST_NMS_TOPK_TRAIN: 50
        POST_NMS_TOPK_TEST: 50
        NMS_THRESH: 0.7
      RESNETS:
        DEPTH: 50
      ROI_BOX_HEAD:
        POOLER_SAMPLING_RATIO: 0
        POOLER_RESOLUTION: 7
      BACKBONE:
        FREEZE_AT: 2
      ROI_HEADS:
        NUM_CLASSES: 1
REGISTER_DATASETS:
  # Change JSON_PATH tp your own path (/home/<user>/Mosquitoes/dataset/v2/coco_json_folds)
  JSON_PATH: "/home/umberto.pereira/Mosquitoes/dataset/v2/coco_json_folds/5folds/40m" # Path to COCO JSON files
  # Change FRAMES_PATH to your own path (/home/<user>/Mosquitoes/dataset/v2/frames)
  FRAMES_PATH: "/home/umberto.pereira/Mosquitoes/dataset/v2/frames" # Path to frames files
  ### The commands are suited for tires, if you want to detect watertanks, then do:
  # JSON_PATH = "/home/<user>/Mosquitoes/dataset/v2/watertanks"
  # FRAMES_PATH = "/home/<user>/Mosquitoes/dataset/v2/frames"
  FOLDS: 5
  OBJECTS: ["tire"] # ["tire", "watertank"]
TRAINING:
  VAL_PERIOD: 1
  TRAINING_NUM_WORKERS: 4
  BATCH_SIZE_PER_IMAGE: 32
  IMAGES_PER_BATCH: 4
  PATIENCE: 1000
  MAX_ITER: 20000
  MIN_DELTA: 0.019
  LEARNING_RATE: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: [] # [initial_step, final_step]
  CUDA_DEVICE: 0
  MODEL_NAME: 'faster_rcnn_R_50_FPN_1x'
  OBJECT: 'tire' # 'tire', 'watertank'
TEST:
  TEST_WEIGHTS: "model_early_stopping.pth"
  OUTPUT_DIR: "outputs/faster_rcnn_R_50_FPN_1x/train_val_test" # outputs/model_name/experiment_name
AUGMENTATION:
  ENABLE: True # True or False

### If you want to kill your process, then do: killall -9 python
